### ISSUE TITLE
关于:F4UART-串口6-DMA中断(传输完成标志位清空)

### ISSUE THREAD

**Issue by zegangYang** [my12doom/pilot2#1]
line 164 : DMA_ClearFlag(DMA2_Stream6, DMA_FLAG_TCIF5);  (×)
line 164 : DMA_ClearFlag(DMA2_Stream6, DMA_FLAG_TCIF6);  (√)

**Comment by my12doom** [comment]
fixed in commit cd3db7707a5cd0e8a671a58f84863a7be4f1a55f.
